packages:
  - apps/*
  - packages/*

catalog:
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/lucide': ^1.2.56
  '@iconify-json/simple-icons': ^1.2.42
  '@iconify-json/vscode-icons': ^1.2.23
  consola: ^3.4.2
  nuxt: ^3.17.6
  tsc: ^2.0.4
  typescript: ^5.8.3
  vue-tsc: ^3.0.1
  zod: ^3.25.76

ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
