packages:
  - apps/*
  - packages/*

catalog:
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/lucide': ^1.2.54
  '@iconify-json/simple-icons': ^1.2.41
  '@iconify-json/vscode-icons': ^1.2.23
  consola: ^3.4.2
  nuxt: ^3.17.6
  tsc: ^2.0.4
  typescript: ^5.8.3
  vue-tsc: ^2.2.10
  zod: ^3.25.67

ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
