packages:
  - apps/*
  - packages/*

catalog:
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/lucide': ^1.2.53
  '@iconify-json/simple-icons': ^1.2.40
  consola: ^3.4.2
  nuxt: ^3.17.5
  tsc: ^2.0.4
  typescript: ^5.8.3
  vue-tsc: ^2.2.10
  zod: ^3.25.67
onlyBuiltDependencies:
  - better-sqlite3
