name: shotly

services:
  shotly:
    image: ghcr.io/shotly/web:local
    env_file:
      - .env
    volumes:
      - .data:/app/.data
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
