name: Nightly

on:
  push:
    paths-ignore:
      - "*.md"
      - ".github/**"
      - "!.github/workflows/nightly.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        package: [web]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}

      - name: Set env
        run: |
          echo "APP_NAME=${{ matrix.package }}" >> $GITHUB_ENV

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/${{ env.APP_NAME }}/Dockerfile
          push: true
          build-args: |
            APP_PUBLIC_VERSION=nightly
          tags: ghcr.io/shotly/${{ env.APP_NAME }}:nightly
