name: Nightly

on:
  push:
    paths-ignore:
      - "*.md"
      - "apps/landing/**"
      - ".github/**"
      - "!.github/workflows/nightly.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        package: [web]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set env
        run: |
          echo "APP_NAME=${{ matrix.package }}" >> $GITHUB_ENV

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/${{ env.APP_NAME }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_PUBLIC_VERSION=nightly
          secrets: |
            NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}
          tags: ghcr.io/shotly/${{ env.APP_NAME }}:nightly
